### ISSUE TITLE
support repeating group

### ISSUE THREAD

**Issue by keith-kl** [leedeper/smart-fix-simulator#1]
Hi, I'm trying to implements a simple trading engine and find your FIX simulator very useful!
One thing I want to ask it whether your simulator supports repeating group tags like 453/448/447/452 ?  I tried to send FIX message with repeating group such as below
8=FIX.4.49=6135=A34=149=EXEC52=20121105-23:24:0656=BANZAI98=0108=30453=2448=a447=D452=17448=a447=D452=11003=XXX10=003

But the XML message output does not seems to parse the groups correctly.  This is the ouput:

```html
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<message>
    <header>
        <field tag="8"><![CDATA[FIX.4.4]]></field>
        <field tag="9"><![CDATA[61]]></field>
        <field tag="34"><![CDATA[1]]></field>
        <field tag="35"><![CDATA[A]]></field>
        <field tag="49"><![CDATA[EXEC]]></field>
        <field tag="52"><![CDATA[20121105-23:24:06]]></field>
        <field tag="56"><![CDATA[BANZAI]]></field>
    </header>
    <body>
        <field tag="98"><![CDATA[0]]></field>
        <field tag="108"><![CDATA[30]]></field>
        <field tag="447"><![CDATA[D]]></field>
        <field tag="448"><![CDATA[a]]></field>
        <field tag="452"><![CDATA[17]]></field>
        <field tag="453"><![CDATA[2]]></field>
    </body>
    <trailer/>
</message>
```

**Comment by leedeper** [comment]
I saw that you sent a Logon message(35="A") for FIX4.4(8="FIX.4.4"), but the fields like 453/448/447/452 you mentioned are not included in the standard version https://github.com/quickfix-j/quickfixj/blob/master/quickfixj-messages/quickfixj-messages-fix44/src/main/resources/FIX44.xml#L44

So it cannot be parsed. However, you may download the link above and modify it according to your wishes, add config it in file quickfixj-server.cfg 

Like this
DataDictionary=./myOwnFIX44.xml
